### ISSUE TITLE
Send Intraledger Flow works

### ISSUE THREAD

**Issue by sandipndev** [GaloyMoney/galoy-cli#126]
Findings:
- Schema is outdated (fix it) - Separate PR possibly touches other mutations bcoz very outdated
- Intraledger inputs although being same as expected doesn't work bcoz error schema mismatch

`galoy-cli send-intraledger --to test --usd 100`
`galoy-cli send-intraledger --to test --btc 1`

**Comment by eshanvaid** [comment]
This has been fixed in #127 and #131
